version: "3.9"
services:
  app:
    image: ghcr.io/afivve/akun-ekagroup-be:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/app_db"
      NODE_ENV: "production"
      PORT: 8080
      HOST: "staging.afive.my.id"
      CORS_ORIGIN: "http://localhost:*" 
      COMMON_RATE_LIMIT_WINDOW_MS: 10000
      COMMON_RATE_LIMIT_MAX_REQUESTS: 2000
      JWT_SECRET: "Hadjpqtrt69UI7347Jhfhud87"
    networks:
      - app-network

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
