services:
  app:
    image: ${IMAGE_NAME}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - ${DOCKER_NETWORKS}

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${DOCKER_MYSQL_VOLUME}
    networks:
      - ${DOCKER_NETWORKS}

networks:
  ${DOCKER_NETWORKS}:
    driver: bridge

volumes:
  mysql-data-production:
