services:
  app:
    image: ${IMAGE_NAME}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network-staging

  mysql:
    image: mariadb:latest
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data-staging:/var/lib/mysql
    networks:
      - app-network-staging

networks:
  app-network-staging:
    driver: bridge

volumes:
  mysql-data-staging:
