services:
  app:
    image: ${IMAGE_NAME}
    container_name: staging_app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - app-network-staging

  mysql:
    image: mariadb:latest
    container_name: staging_mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${DOCKER_MYSQL_VOLUME_PATH}
    networks:
      - app-network-staging

networks:
  app-network-staging:
    driver: bridge

volumes:
  mysql-data-staging:
